Fix unexpected argument panic in `pest_debugger`
Fixes a panic when you provide the debugger executable with an argument
it does not expect. It now exits gracefully.

before:
```
$ pest_debugger random args
thread 'main' panicked at 'internal error: entered unreachable code', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/pest_debugger-2.5.0/src/main.rs:259:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

after:
```
$ pest_debugger random args
Error: unexpected argument `random`
Error: unexpected argument `args`
```